#!/usr/bin/env python3.13
""" module to convert a give jupyter notebook to tex
    and remove the preambles """

import os
import sys

fileName = sys.argv[1] # variable from the command line
# build the command to execute
command = "jupyter nbconvert --TagRemovePreprocessor.enabled=True --TagRemovePreprocessor.remove_cell_tags='noPrint' --to latex "+fileName
os.system(command) # execute the nbconvert command

texFile = fileName[:-6]+".tex" # strip the ipynb extension and add tex
# open the tex file and remove the preambles
with open(texFile,'r') as f:
    lines = f.readlines()
with open(texFile,'w') as f:
    f.writelines(lines[392:-1])